import type { HelpArticle } from '../types';

export const FINANCEIRO_ARTICLES: HelpArticle[] = [
  {
    slug: 'contas-a-pagar',
    title: 'O que é Contas a pagar',
    module: 'financeiro',
    summary: 'Títulos gerados a partir das despesas aprovadas das viagens.',
    keywords: ['contas a pagar', 'título', 'pagamento', 'vencido'],
    content: {
      oQueE: 'Contas a pagar reúne os títulos gerados a partir das despesas aprovadas das viagens, além de títulos lançados manualmente.',
      paraQueServe: 'Controlar o que a transportadora tem a pagar, por vencimento e categoria.',
      comoFazer: [
        'Acesse "Contas a pagar" no menu Financeiro.',
        'Acompanhe o painel de total a pagar, pago, em aberto e vencido.',
        'Registre o pagamento de um título, total ou parcial.',
      ],
      oQueAconteceDepois: 'Um título pago parcialmente muda para "Pago parcialmente"; quando o valor total é pago, vai para "Pago".',
      atencao: '"Vencido" é calculado automaticamente pela data -- não é um status que alguém escolhe.',
    },
    relatedSlugs: ['despesas-de-viagem', 'status-financeiro'],
  },
  {
    slug: 'contas-a-receber',
    title: 'O que é Contas a receber',
    module: 'financeiro',
    summary: 'Títulos gerados a partir do faturamento das viagens.',
    keywords: ['contas a receber', 'título', 'recebimento', 'vencido'],
    content: {
      oQueE: 'Contas a receber reúne os títulos gerados a partir do faturamento das viagens, além de títulos lançados manualmente.',
      paraQueServe: 'Controlar o que a transportadora tem a receber de cada cliente, por vencimento.',
      comoFazer: [
        'Acesse "Contas a receber" no menu Financeiro.',
        'Registre o recebimento de um título, total ou parcial.',
      ],
      oQueAconteceDepois: 'Um título recebido parcialmente muda para "Recebido parcialmente"; quando o valor total é recebido, vai para "Recebido".',
    },
    relatedSlugs: ['faturamento', 'status-financeiro'],
  },
  {
    slug: 'faturamento',
    title: 'Como uma viagem vira faturamento',
    module: 'financeiro',
    summary: 'Do valor contratado ao recebimento, passo a passo.',
    keywords: ['faturamento', 'billing', 'faturar', 'nota fiscal'],
    content: {
      oQueE: 'O faturamento acompanha o caminho de uma viagem do valor contratado até o recebimento: contratado → calculado → faturado → recebido.',
      paraQueServe: 'Conferir se toda viagem elegível foi faturada corretamente e identificar o que ainda falta faturar.',
      comoFazer: [
        'Acesse "Faturamento" (dentro de Fretes/Gestão da frota).',
        'Na aba "Viagens elegíveis", veja as viagens ainda sem faturamento.',
        'Inicie o faturamento de uma viagem -- ele nasce como "Rascunho" e muda conforme o valor é confirmado, faturado e recebido.',
      ],
      oQueAconteceDepois: 'Um faturamento gera (ou se relaciona com) um título em Contas a receber.',
      atencao: 'Hoje o total recebido sempre acompanha o total faturado, porque não há uma integração com meio de pagamento -- o recebimento é sempre um registro manual.',
    },
    relatedSlugs: ['contas-a-receber'],
  },
  {
    slug: 'periodos-financeiros',
    title: 'O que é o fechamento de período financeiro',
    module: 'financeiro',
    summary: 'Como e por que um período é fechado.',
    keywords: ['período', 'fechamento', 'competência', 'fechar mês'],
    content: {
      oQueE: 'Um período financeiro representa um mês de competência (formato AAAA-MM), que pode estar Aberto ou Fechado.',
      paraQueServe: 'Fechar um período impede novos lançamentos com data de competência naquele mês, sem alterar nenhum dado já existente.',
      comoFazer: [
        'Acesse "Períodos financeiros".',
        'Abra o período do mês desejado -- a tela mostra um resumo (recebido, pago, contas em aberto) e eventuais inconsistências de conciliação.',
        'Se não houver inconsistência crítica, clique em "Fechar período" e confirme.',
      ],
      oQueAconteceDepois: 'Lançamentos com data de competência dentro de um período fechado não são mais permitidos.',
      atencao: 'O fechamento é irreversível nesta versão do sistema: um período fechado não pode ser reaberto. Se houver inconsistência crítica de conciliação, o fechamento é bloqueado até que ela seja resolvida.',
    },
    relatedSlugs: ['conciliacao-bancaria'],
  },
  {
    slug: 'conciliacao-bancaria',
    title: 'O que é a conciliação bancária',
    module: 'financeiro',
    summary: 'Conferência entre o extrato importado e o registro interno.',
    keywords: ['conciliação', 'extrato', 'banco', 'csv'],
    content: {
      oQueE: 'A conciliação bancária confere as movimentações de um extrato importado (CSV) contra os lançamentos já registrados no sistema.',
      paraQueServe: 'Identificar diferenças entre o que o banco registrou e o que o sistema tem lançado.',
      comoFazer: [
        'Acesse "Conciliação bancária" e importe o extrato em CSV.',
        'Para cada movimentação, concilie manualmente com o lançamento correspondente.',
      ],
      oQueAconteceDepois: 'Cada movimentação fica como Pendente, Conciliada ou Divergente.',
      atencao: 'Importar o extrato nunca cria um lançamento novo -- só a conciliação vincula as duas pontas. O saldo bancário oficial não é calculado aqui.',
    },
    relatedSlugs: ['periodos-financeiros'],
  },
  {
    slug: 'fluxo-de-caixa',
    title: 'O que mostra o fluxo de caixa',
    module: 'financeiro',
    summary: 'Projeção de liquidez sobre contas a pagar e a receber.',
    keywords: ['fluxo de caixa', 'caixa', 'liquidez', 'projeção'],
    content: {
      oQueE: 'O fluxo de caixa projeta a liquidez com base nos títulos de contas a receber e a pagar já lançados.',
      paraQueServe: 'Ter uma visão de saldo projetado, vencimentos por mês e quais clientes têm maior valor em aberto.',
      atencao: 'É uma projeção sobre títulos já lançados -- nunca representa o saldo bancário real.',
    },
    relatedSlugs: ['contas-a-pagar', 'contas-a-receber'],
  },
  {
    slug: 'rentabilidade-por-cliente',
    title: 'Como ver a rentabilidade por cliente',
    module: 'financeiro',
    summary: 'Receita e custo real das viagens, consolidados por cliente.',
    keywords: ['rentabilidade', 'margem', 'lucro', 'cliente'],
    content: {
      oQueE: 'A rentabilidade por cliente consolida a receita e o custo real das viagens de cada cliente.',
      paraQueServe: 'Identificar quais clientes dão mais (ou menos) resultado e margem para a transportadora.',
      comoFazer: ['Acesse "Rentabilidade por Cliente" no menu Financeiro e consulte o ranking por resultado e por margem.'],
    },
  },
  {
    slug: 'auditoria-financeira',
    title: 'O que é a auditoria financeira',
    module: 'financeiro',
    summary: 'Histórico de alterações em contas e períodos financeiros.',
    keywords: ['auditoria', 'log', 'histórico', 'rastreabilidade'],
    content: {
      oQueE: 'A auditoria financeira mostra o histórico de alterações feitas em contas a receber, a pagar e períodos financeiros.',
      paraQueServe: 'Rastrear quem alterou o quê, e quando, nos registros financeiros.',
      comoFazer: ['Acesse "Auditoria financeira" e filtre por entidade, ação ou período.', 'Clique numa linha para ver o detalhe da alteração.'],
      atencao: 'É uma tela de consulta -- nada pode ser editado ou apagado por ali.',
    },
  },
  {
    slug: 'custos-da-frota',
    title: 'Como ver os custos da frota',
    module: 'financeiro',
    summary: 'Combustível, manutenção, pneus, pedágio e custo por km.',
    keywords: ['custo', 'custo por km', 'combustível', 'manutenção'],
    content: {
      oQueE: 'A tela de custos reúne os gastos realmente realizados: combustível, manutenção, pneus, pedágio e outras despesas aprovadas.',
      paraQueServe: 'Entender quanto custa, de fato, operar a frota, incluindo o custo por quilômetro rodado.',
      comoFazer: ['Acesse "Custos" (dentro de Gestão da frota) para ver o total por categoria e o custo por km.'],
      atencao: 'Só entram valores já realizados -- nunca uma estimativa. Quando não há distância real suficiente, o custo por km aparece como indisponível, em vez de mostrar um valor incorreto.',
    },
  },
  {
    slug: 'adiantamentos',
    title: 'O que são os adiantamentos',
    module: 'financeiro',
    summary: 'Valores pagos a motoristas para despesas de viagem.',
    keywords: ['adiantamento', 'vale', 'motorista'],
    content: {
      oQueE: 'Um adiantamento é um valor pago a um motorista, antecipadamente, para cobrir despesas de uma viagem.',
      paraQueServe: 'Registrar e controlar valores adiantados, por motorista e viagem.',
      comoFazer: ['Acesse "Adiantamentos" e registre o valor, a data e o motorista.'],
    },
  },
  {
    slug: 'documentos-fiscais',
    title: 'O que são os documentos fiscais da operação',
    module: 'financeiro',
    summary: 'CT-e, MDF-e, NF-e e comprovantes vinculados às viagens.',
    keywords: ['cte', 'mdfe', 'nfe', 'documento fiscal', 'ciot'],
    content: {
      oQueE: 'São os documentos fiscais e operacionais da transportadora: CT-e, MDF-e, NF-e, CIOT, comprovante de entrega, entre outros.',
      paraQueServe: 'Reunir e conferir, por viagem, os documentos que comprovam o transporte.',
      comoFazer: [
        'Acesse "Documentos fiscais" (dentro de Gestão da frota).',
        'Importe o XML do documento ou envie o arquivo manualmente.',
        'O vínculo entre MDF-e e os CT-e/NF-e relacionados é feito pela chave do documento, nunca por aproximação.',
      ],
      oQueAconteceDepois: 'Cada documento recebe um status: Pendente, Reconhecido, Inválido ou Cancelado.',
      atencao: 'O status "Reconhecido" indica que a estrutura básica do documento foi entendida pelo sistema -- não é uma validação oficial perante a SEFAZ.',
    },
    relatedSlugs: ['comprovante-de-entrega'],
  },
];
